# Generated by Django 2.2.6 on 2019-11-03 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('speaks_profesionally', models.IntegerField(blank=True, null=True)),
                ('fellows_university', models.CharField(blank=True, max_length=255, null=True)),
                ('eye_contact', models.IntegerField(blank=True, null=True)),
                ('handshake', models.IntegerField(blank=True, null=True)),
                ('body_language', models.IntegerField(blank=True, null=True)),
                ('specific_relevant_examples', models.IntegerField(blank=True, null=True)),
                ('transferable_skills', models.IntegerField(blank=True, null=True)),
                ('clear_concise', models.IntegerField(blank=True, null=True)),
                ('compelling', models.IntegerField(blank=True, null=True)),
                ('answers', models.IntegerField(blank=True, null=True)),
                ('continues_connection', models.IntegerField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_in', models.BooleanField(default=False)),
                ('role', models.CharField(max_length=255)),
            ],
        ),
    ]
